kind: Service
apiVersion: v1
metadata:
  name: simple_app_service
spec:
  type: NodePort
  selector:
    app: simple_app
  ports:
  - protocol: TCP 
    port: 8080
    nodePort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-app-deployment
  lables:
    app: flask_test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask_test
  template:
    metadata:
      labels:
        app: flask_test
    spec:
      containers:
      - name: flask_test
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
