kind: Service
apiVersion: v1
metadata:
  name: flask-test-service
spec:
  type: NodePort
  selector:
    app: flask-test
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-deployment
  labels:
    app: flask-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-test
  template:
    metadata:
      labels:
        app: flask-test
    spec:
      containers:
      - name: flask-test
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
